[project]
name = "robohack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "opencv-python>=4.7.0",
    "requests>=2.31.0",
    "fastapi>=0.95.0",
    "uvicorn[standard]>=0.22.0",
    "python-multipart>=0.0.6",
    "pillow>=10.0.0",
    "transformers==4.53.3",
    "accelerate>=0.20.3",
    "torch>=2.2.0",
    "safetensors>=0.3.0",
    "bitsandbytes>=0.39.0 ; platform_system != 'Darwin'",
    "timm>=0.9.10,<1.0.0",
    "uv>=0.9.5",
    "pip>=25.2",
    "lerobot[feetech]>=0.4.0",
    "grpcio>=1.76.0",
    "protobuf>=6.3",
    "networkx>=3.5",
    "pydantic>=1.10,<2.0",
    "ollama>=0.3.3",
    "sounddevice>=0.5.3",
    "soundfile>=0.13.1",
    "scipy>=1.16.2",
    "packaging>=24.2,<26.0",
    "num2words>=0.5.14",
]

[tool.uv.extra-build-dependencies]
# FlashAttention requires torch as build dependency
flash-attn = ["torch>=2.2.0"]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
